[project]
name = "databs-social-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["atproto>=0.0.55"]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "tqdm>=4.67.0",
]
